files:
  - source: /*.json
    translation: /translations/json/%locale%/%original_file_name%
  - source: Example.xml
    translation: /olga/%language%_%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - /<data>/</string>
