files:
  - source: /en.ini
    translation: /translations/%locale%.%file_extension%
  - source: /*.json
    ignore:
      - /Example.json
    translation: /translations/%file_name%_%two_letters_code%.%file_extension%
    translation_replace: &ref__en
      _en: 
  - source: /index.twig
    dest : /index.html
    translation: /translations/%file_name%-%two_letters_code%.twig
    type: html
